name: Build

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/harm-matthias-harms/postgres-wal-g
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/harm-matthias-harms/postgres-wal-g
      - run: gh api repos/${{ github.repository }}/packages/container/${{ steps.meta.outputs.tags }} -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
