name: Test

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/harm-matthias-harms/postgres-wal-g
      - run: gh api repos/${{ github.repository }}/packages/container/${{ steps.meta.outputs.tags }} -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
