name: Test

on:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml
  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/harm-matthias-harms/postgres-wal-g
      - name: Get version ID
        id: get_version_id
        run: |
          VERSIONS=$(gh api users/harm-matthias-harms/packages/container/postgres-wal-g/versions)
          VERSION_ID=$(echo $VERSIONS | jq -r '.[] | select(.metadata.container.tags[0] == "${{ steps.meta.outputs.version }}") | .id')
          echo "::set-output name=version_id::$VERSION_ID"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete version
        run: |
          gh api users/harm-matthias-harms/packages/container/postgres-wal-g/versions/${{ steps.get_version_id.outputs.version_id }} -X DELETE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
